// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RadioIntercepts.Infrastructure.Data;

#nullable disable

namespace RadioIntercepts.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260114054427_AddIndexes")]
    partial class AddIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RadioIntercepts.Core.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Areas_Name");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("RadioIntercepts.Core.Models.Callsign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Callsigns_Name");

                    b.ToTable("Callsigns");
                });

            modelBuilder.Entity("RadioIntercepts.Core.Models.Frequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("IX_Frequencies_Value");

                    b.ToTable("Frequencies");
                });

            modelBuilder.Entity("RadioIntercepts.Core.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dialog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FrequencyId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("DateTime")
                        .HasDatabaseName("IX_Messages_DateTime");

                    b.HasIndex("FrequencyId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("RadioIntercepts.Core.Models.MessageCallsign", b =>
                {
                    b.Property<long>("MessageId")
                        .HasColumnType("bigint");

                    b.Property<int>("CallsignId")
                        .HasColumnType("int");

                    b.HasKey("MessageId", "CallsignId");

                    b.HasIndex("CallsignId");

                    b.ToTable("MessageCallsigns");
                });

            modelBuilder.Entity("RadioIntercepts.Core.Models.Message", b =>
                {
                    b.HasOne("RadioIntercepts.Core.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadioIntercepts.Core.Models.Frequency", "Frequency")
                        .WithMany()
                        .HasForeignKey("FrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Frequency");
                });

            modelBuilder.Entity("RadioIntercepts.Core.Models.MessageCallsign", b =>
                {
                    b.HasOne("RadioIntercepts.Core.Models.Callsign", "Callsign")
                        .WithMany()
                        .HasForeignKey("CallsignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RadioIntercepts.Core.Models.Message", "Message")
                        .WithMany("MessageCallsigns")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Callsign");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("RadioIntercepts.Core.Models.Message", b =>
                {
                    b.Navigation("MessageCallsigns");
                });
#pragma warning restore 612, 618
        }
    }
}
